# Generated by Django 5.2.17 on 2026-09-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0130_schoolyeararchive_complete_school_work_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="report_review_enabled",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="إظهار لوحة فحص جاهزية التقرير قبل الحفظ. الفحص البنيوي يعمل دون استهلاك رصيد، والفحص الذكي يستهلك محاولة من رصيد المستخدم اليومي.",
                verbose_name="إظهار فحص جاهزية التقرير",
            ),
        ),
    ]
