# Generated by Django 5.2.17 on 2026-09-03 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0131_platform_settings_report_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="وقت النداء"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("mansour", "منصور"),
                            ("mansour-rewrite", "منصور — إعادة صياغة"),
                            ("report-improve", "تحسين الصياغة"),
                            ("report-review", "فحص الجاهزية"),
                            ("transcription", "تفريغ صوتي"),
                            ("voice-polish", "تجميل التفريغ"),
                            ("other", "غير ذلك"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="المرحلة",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="النموذج"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "نجح"),
                            ("truncated", "مبتور"),
                            ("failed", "فشل"),
                        ],
                        db_index=True,
                        default="success",
                        max_length=16,
                        verbose_name="النتيجة",
                    ),
                ),
                (
                    "error_kind",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اسم الاستثناء أو رمز HTTP. لا يحمل نص الرسالة.",
                        max_length=64,
                        verbose_name="نوع العطل",
                    ),
                ),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="رموز الإدخال"),
                ),
                (
                    "cached_input_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="الدليل الوحيد على أن تخزين البادئة يعمل في الإنتاج.",
                        verbose_name="المقروء من المخزَّن",
                    ),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="رموز الإخراج"),
                ),
                (
                    "reasoning_tokens",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="محسوبة ضمن الإخراج، وتُفرد لأنها تلتهم سقف الرموز وتسبّب البتر.",
                        verbose_name="رموز التفكير",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="زمن النداء (مللي ثانية)"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="محسوبة بسعر لحظة الاستهلاك. تبقى فارغة إن لم يُضبط سعر للنموذج.",
                        max_digits=12,
                        null=True,
                        verbose_name="الكلفة التقديرية (دولار)",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_events",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "استهلاك ذكاء اصطناعي",
                "verbose_name_plural": "استهلاك الذكاء الاصطناعي",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["stage", "created_at"],
                        name="reports_aiu_stage_05bdc4_idx",
                    ),
                    models.Index(
                        fields=["school", "created_at"],
                        name="reports_aiu_school__d9067b_idx",
                    ),
                    models.Index(
                        fields=["outcome", "created_at"],
                        name="reports_aiu_outcome_5a59cf_idx",
                    ),
                ],
            },
        ),
    ]
