# Generated by Django 5.2.17 on 2026-09-22 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0137_handwritten_circular_signatures"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSendSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_key", models.UUIDField(verbose_name="معرّف عملية الإرسال")),
                (
                    "payload_fingerprint",
                    models.CharField(max_length=64, verbose_name="بصمة الطلب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أُنشئ في"
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="send_submission",
                        to="reports.notification",
                        verbose_name="الإشعار الناتج",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_send_submissions",
                        to="reports.school",
                        verbose_name="نطاق المدرسة",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_send_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "db_table": "reports_notification_send_submission",
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender", "submission_key"),
                        name="uniq_notif_send_sender_key",
                    )
                ],
            },
        ),
    ]
