# Generated by Django 5.2.17 on 2026-09-23 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0138_notification_send_idempotency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusageevent",
            name="stage",
            field=models.CharField(
                choices=[
                    ("mansour", "منصور"),
                    ("mansour-rewrite", "منصور — إعادة صياغة"),
                    ("report-improve", "تحسين الصياغة"),
                    ("report-review", "فحص الجاهزية"),
                    ("transcription", "تفريغ صوتي"),
                    ("voice-polish", "تجميل التفريغ"),
                    ("conversion-outreach", "مساعد التحويل"),
                    ("other", "غير ذلك"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="المرحلة",
            ),
        ),
        migrations.CreateModel(
            name="SchoolConversionOutreach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("activate", "إكمال أول استفادة"),
                            ("convert", "التحويل إلى اشتراك مدفوع"),
                            ("renew", "تجديد اشتراك مدفوع"),
                            ("recover", "استعادة مدرسة منتهية"),
                        ],
                        default="convert",
                        max_length=16,
                        verbose_name="الهدف",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("executive", "تنفيذي وواثق"),
                            ("supportive", "مساند وودود"),
                            ("concise", "مختصر ومباشر"),
                        ],
                        default="executive",
                        max_length=16,
                        verbose_name="نبرة الرسالة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة بانتظار المراجعة"),
                            ("sending", "جارٍ الإرسال"),
                            ("sent", "أُرسلت"),
                            ("partial", "أُرسلت جزئيًا"),
                            ("failed", "تعذر الإرسال"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(default=dict, verbose_name="لقطة المؤشرات"),
                ),
                (
                    "analysis_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="تحليل الحالة"
                    ),
                ),
                (
                    "recommended_action",
                    models.TextField(
                        blank=True, default="", verbose_name="الإجراء المقترح"
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="عنوان البريد",
                    ),
                ),
                (
                    "email_body",
                    models.TextField(blank=True, default="", verbose_name="نص البريد"),
                ),
                (
                    "in_app_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="عنوان الإشعار",
                    ),
                ),
                (
                    "in_app_body",
                    models.TextField(blank=True, default="", verbose_name="نص الإشعار"),
                ),
                (
                    "whatsapp_body",
                    models.TextField(
                        blank=True, default="", verbose_name="نص واتساب المقترح"
                    ),
                ),
                (
                    "call_script",
                    models.JSONField(
                        blank=True, default=list, verbose_name="محاور المكالمة"
                    ),
                ),
                (
                    "ai_generated",
                    models.BooleanField(
                        default=False, verbose_name="مولدة بالذكاء الاصطناعي"
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="نموذج الذكاء الاصطناعي",
                    ),
                ),
                (
                    "requested_channels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="القنوات المطلوبة"
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "غير مطلوبة"),
                            ("pending", "بانتظار الإرسال"),
                            ("sent", "أُرسلت"),
                            ("failed", "فشلت"),
                        ],
                        default="not_requested",
                        max_length=16,
                        verbose_name="حالة البريد",
                    ),
                ),
                (
                    "in_app_status",
                    models.CharField(
                        choices=[
                            ("not_requested", "غير مطلوبة"),
                            ("pending", "بانتظار الإرسال"),
                            ("sent", "أُرسلت"),
                            ("failed", "فشلت"),
                        ],
                        default="not_requested",
                        max_length=16,
                        verbose_name="حالة الإشعار الداخلي",
                    ),
                ),
                (
                    "platform_email_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="رسائل البريد الناتجة"
                    ),
                ),
                (
                    "delivery_result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="نتيجة الإرسال"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, default="", verbose_name="سبب التعذر"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="اعتمدت في"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أرسلت في"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="أنشئت في"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="حدثت في"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_outreaches_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعتمدها",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_outreaches_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشأها",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_outreaches",
                        to="reports.notification",
                        verbose_name="الإشعار الناتج",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_outreaches",
                        to="reports.school",
                        verbose_name="المدرسة",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversion_outreaches",
                        to="reports.schoolsubscription",
                        verbose_name="لقطة الاشتراك",
                    ),
                ),
            ],
            options={
                "verbose_name": "تواصل تحويل مدرسة",
                "verbose_name_plural": "تواصلات تحويل المدارس",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["school", "-created_at"], name="rpt_conv_school_recent"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="rpt_conv_status_recent"
                    ),
                ],
            },
        ),
    ]
