# Generated by Django 5.2.17 on 2026-09-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0139_school_conversion_outreach"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "ذكر"), ("female", "أنثى")],
                default="",
                max_length=6,
                verbose_name="الجنس",
            ),
        ),
    ]
