# Generated by Django 5.2.17 on 2026-09-24 17:10

import django.core.validators
import django.db.models.deletion
import personal.models
import reports.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        max_length=200, verbose_name="اسم المدرسة للتعريف"
                    ),
                ),
                (
                    "principal_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="اسم مدير المدرسة للتعريف",
                    ),
                ),
                (
                    "school_stage",
                    models.CharField(blank=True, max_length=50, verbose_name="المرحلة"),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=120, verbose_name="التخصص"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_workspace",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مساحة معلم شخصية",
                "verbose_name_plural": "مساحات المعلمين الشخصية",
            },
        ),
        migrations.CreateModel(
            name="PersonalReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان العمل")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نوع العمل"
                    ),
                ),
                ("report_date", models.DateField(verbose_name="تاريخ العمل")),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="السنة الدراسية"),
                ),
                ("description", models.TextField(verbose_name="وصف العمل")),
                ("goals", models.TextField(blank=True, verbose_name="الأهداف")),
                (
                    "implementation",
                    models.TextField(blank=True, verbose_name="التنفيذ"),
                ),
                ("results", models.TextField(blank=True, verbose_name="النتائج")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="التوصيات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("complete", "مكتمل"),
                            ("archived", "مؤرشف"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "teacher_name",
                    models.CharField(
                        max_length=150, verbose_name="اسم المعلم وقت الحفظ"
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        max_length=200, verbose_name="اسم المدرسة وقت الحفظ"
                    ),
                ),
                (
                    "principal_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="اسم المدير وقت الحفظ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير معلم شخصي",
                "verbose_name_plural": "تقارير المعلمين الشخصية",
                "ordering": ["-report_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الشاهد"),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="السنة الدراسية"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=personal.models.personal_evidence_path,
                        validators=[
                            reports.validators.validate_circular_attachment_file,
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            ),
                        ],
                        verbose_name="الملف",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="رابط الشاهد")),
                ("file_size", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="personal.personalreport",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاهد شخصي",
                "verbose_name_plural": "شواهد شخصية",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="personalreport",
            index=models.Index(
                fields=["workspace", "academic_year", "status"],
                name="personal_pe_workspa_249283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personalevidence",
            index=models.Index(
                fields=["workspace", "academic_year"],
                name="personal_pe_workspa_7240bc_idx",
            ),
        ),
    ]
