# Generated by Django 5.2.17 on 2026-09-24 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=40, unique=True, verbose_name="رمز الباقة"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الباقة")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="السعر بالريال",
                    ),
                ),
                (
                    "max_reports",
                    models.PositiveIntegerField(
                        default=500, verbose_name="الحد الأعلى للتقارير"
                    ),
                ),
                (
                    "max_evidence",
                    models.PositiveIntegerField(
                        default=250, verbose_name="الحد الأعلى للشواهد"
                    ),
                ),
                (
                    "storage_limit_mb",
                    models.PositiveIntegerField(
                        default=500, verbose_name="سعة الملفات بالميجابايت"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="متاحة للاشتراكات الجديدة"
                    ),
                ),
            ],
            options={
                "verbose_name": "باقة معلم شخصية",
                "verbose_name_plural": "باقات المعلمين الشخصية",
            },
        ),
        migrations.CreateModel(
            name="PersonalSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personal.personalplan",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراك معلم شخصي",
                "verbose_name_plural": "اشتراكات المعلمين الشخصية",
            },
        ),
    ]
