# Generated by Django 5.2.17 on 2026-09-24 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_personalplan_personalsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalplan",
            name="description",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="وصف مختصر للعرض"
            ),
        ),
        migrations.AddField(
            model_name="personalplan",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="ترتيب العرض"
            ),
        ),
        migrations.AddField(
            model_name="personalplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="صفر للباقة المجانية المستمرة؛ الباقات المدفوعة تتطلب مدة محددة.",
                verbose_name="مدة الاشتراك بالأيام",
            ),
        ),
        migrations.AddField(
            model_name="personalplan",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="تظهر في صفحة الهبوط"),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="max_evidence",
            field=models.PositiveIntegerField(
                default=250,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="الحد الأعلى للشواهد",
            ),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="max_reports",
            field=models.PositiveIntegerField(
                default=500,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="الحد الأعلى للتقارير",
            ),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="السعر بالريال",
            ),
        ),
        migrations.AlterField(
            model_name="personalplan",
            name="storage_limit_mb",
            field=models.PositiveIntegerField(
                default=500,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="سعة الملفات بالميجابايت",
            ),
        ),
    ]
