# Generated by Django 5.2.17 on 2026-09-24 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_seed_personal_free_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        max_length=100, verbose_name="اسم الباقة وقت الشراء"
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="مدة الباقة وقت الشراء"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="المبلغ بالريال"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        max_length=150, verbose_name="اسم المشترك وقت الشراء"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="بريد الفاتورة"),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="المدرسة للتعريف وقت الشراء",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "بانتظار الدفع"),
                            ("paid", "مدفوع ومفعّل"),
                            ("failed", "فشل الدفع"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "gateway_invoice_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=160
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "gateway_status",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_sending_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="personal.personalplan",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة مساحة شخصية",
                "verbose_name_plural": "دفعات المساحات الشخصية",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="personal_pe_status_77c67d_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("gateway_invoice_id", ""), _negated=True),
                        fields=("gateway_invoice_id",),
                        name="personal_payment_gateway_invoice_uniq",
                    )
                ],
            },
        ),
    ]
