# Generated by Django 5.2.17 on 2026-09-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0005_personalpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="صفر للباقة المستمرة؛ الباقات المدفوعة تتطلب مدة محددة.",
                verbose_name="مدة الاشتراك بالأيام",
            ),
        ),
    ]
