# Generated by Django 5.2.17 on 2026-09-25 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0006_alter_personalplan_duration_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="personalreport",
            name="beneficiaries_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="عدد المستفيدين"
            ),
        ),
        migrations.AddField(
            model_name="personalreport",
            name="show_beneficiaries",
            field=models.BooleanField(
                default=False, verbose_name="إظهار عدد المستفيدين"
            ),
        ),
        migrations.AddField(
            model_name="personalreport",
            name="show_goals",
            field=models.BooleanField(default=True, verbose_name="إظهار الأهداف"),
        ),
        migrations.AddField(
            model_name="personalreport",
            name="show_implementation",
            field=models.BooleanField(default=True, verbose_name="إظهار آلية التنفيذ"),
        ),
        migrations.AddField(
            model_name="personalreport",
            name="show_recommendations",
            field=models.BooleanField(default=True, verbose_name="إظهار التوصيات"),
        ),
        migrations.AddField(
            model_name="personalreport",
            name="show_results",
            field=models.BooleanField(default=True, verbose_name="إظهار النتائج"),
        ),
        migrations.AddField(
            model_name="personalworkspace",
            name="current_academic_year",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="السنة الدراسية الحالية",
            ),
        ),
        migrations.CreateModel(
            name="PersonalInitiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="السنة الدراسية"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المبادرة"),
                ),
                ("summary", models.TextField(verbose_name="الفكرة والتنفيذ")),
                ("impact", models.TextField(blank=True, verbose_name="الأثر والنتائج")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("complete", "مكتملة"),
                            ("archived", "مؤرشفة"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiatives",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="personalevidence",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evidence",
                to="personal.personalinitiative",
            ),
        ),
        migrations.CreateModel(
            name="PersonalNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=160, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_notices_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalNoticeRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="personal.personalnotice",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalAcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(max_length=20, verbose_name="السنة الدراسية"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="أُرشفت في"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-value"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "value"),
                        name="unique_personal_workspace_year",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="personalinitiative",
            index=models.Index(
                fields=["workspace", "academic_year", "status"],
                name="personal_pe_workspa_7c24f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="personalnoticerecipient",
            index=models.Index(
                fields=["workspace", "read_at"], name="personal_pe_workspa_e0fdfe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personalnoticerecipient",
            constraint=models.UniqueConstraint(
                fields=("notice", "workspace"), name="unique_personal_notice_recipient"
            ),
        ),
    ]
