# Generated by Django 5.2.17 on 2026-09-25 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0008_backfill_personal_years"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalPortfolioSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="السنة الدراسية"),
                ),
                (
                    "code",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1- أداء الواجبات الوظيفية"),
                            (2, "2- التفاعل مع المجتمع المهني"),
                            (3, "3- التفاعل مع أولياء الأمور"),
                            (4, "4- التنوع في استراتيجيات التدريس"),
                            (5, "5- تحسين نتائج المتعلمين"),
                            (6, "6- إعداد وتنفيذ خطة التعلم"),
                            (7, "7- توظيف تقنيات ووسائل التعلم المناسبة"),
                            (8, "8- تهيئة بيئة تعليمية"),
                            (9, "9- الإدارة الصفية"),
                            (10, "10- تحليل نتائج المتعلمين وتشخيص مستوياتهم"),
                            (11, "11- تنوع أساليب التقويم"),
                        ],
                        verbose_name="المحور",
                    ),
                ),
                (
                    "teacher_notes",
                    models.TextField(blank=True, verbose_name="وصف الممارسة"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_sections",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalPortfolioReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_links",
                        to="personal.personalreport",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_reports",
                        to="personal.personalportfoliosection",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalPortfolioEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_links",
                        to="personal.personalevidence",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_evidence",
                        to="personal.personalportfoliosection",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="personalportfoliosection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "academic_year", "code"),
                name="unique_personal_portfolio_axis",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalportfolioreport",
            constraint=models.UniqueConstraint(
                fields=("section", "report"), name="unique_personal_axis_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="personalportfolioevidence",
            constraint=models.UniqueConstraint(
                fields=("section", "evidence"), name="unique_personal_axis_evidence"
            ),
        ),
    ]
