# Generated by Django 5.2.17 on 2026-09-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0009_portfolio_sections_and_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalacademicyear",
            name="contact_info",
            field=models.TextField(blank=True, verbose_name="بيانات التواصل"),
        ),
        migrations.AddField(
            model_name="personalacademicyear",
            name="professional_experience",
            field=models.TextField(blank=True, verbose_name="الخبرات المهنية"),
        ),
        migrations.AddField(
            model_name="personalacademicyear",
            name="qualifications",
            field=models.TextField(blank=True, verbose_name="المؤهلات"),
        ),
        migrations.AddField(
            model_name="personalacademicyear",
            name="specialization",
            field=models.TextField(blank=True, verbose_name="التخصص"),
        ),
        migrations.AddField(
            model_name="personalacademicyear",
            name="subjects_taught",
            field=models.TextField(blank=True, verbose_name="مواد التدريس"),
        ),
        migrations.AddField(
            model_name="personalacademicyear",
            name="teaching_load",
            field=models.TextField(blank=True, verbose_name="نصاب الحصص"),
        ),
    ]
