# Generated by Django 5.2.17 on 2026-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0011_personal_report_optional_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinitiative",
            name="is_best_practice",
            field=models.BooleanField(default=False, verbose_name="ممارسة ناجحة"),
        ),
    ]
