# Generated by Django 5.2.17 on 2026-09-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0014_personal_report_trash"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("report", "تقرير"), ("portfolio", "ملف إنجاز")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="personal.personalreport",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="personal.personalworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "kind", "is_active"],
                        name="personal_pe_workspa_9de889_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "report"), ("report__isnull", False)),
                            models.Q(("kind", "portfolio"), ("report__isnull", True)),
                            _connector="OR",
                        ),
                        name="personal_share_target_matches_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("kind", "report")),
                        fields=("workspace", "report"),
                        name="unique_active_personal_report_share",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True), ("kind", "portfolio")),
                        fields=("workspace", "academic_year"),
                        name="unique_active_personal_portfolio_share",
                    ),
                ],
            },
        ),
    ]
