# Generated by Django 5.2.17 on 2026-09-25 17:00

import django.core.validators
import personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0015_personal_share_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalevidence",
            name="report_caption",
            field=models.CharField(
                blank=True,
                default="",
                max_length=220,
                verbose_name="وصف الشاهد في التقرير",
            ),
        ),
        migrations.AlterField(
            model_name="personalevidence",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=personal.models.personal_evidence_path,
                validators=[
                    personal.models.validate_personal_evidence_file,
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png", "webp"]
                    ),
                ],
                verbose_name="الملف",
            ),
        ),
    ]
