# Generated by Django 5.2.17 on 2026-09-25 17:12

import django.core.validators
from django.db import migrations, models


def enable_existing_paid_plans(apps, schema_editor):
    plan_model = apps.get_model("personal", "PersonalPlan")
    plan_model.objects.exclude(code="personal_free").filter(price__gt=0).update(
        report_ai_daily_limit=3,
        voice_report_daily_limit=3,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0016_personalevidence_report_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalplan",
            name="report_ai_daily_limit",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="صفر لتعطيل التحسين في الباقة؛ الباقة الأساسية المجانية لا تمنح استخدامًا مدفوعًا.",
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="تحسينات التقارير يوميًا",
            ),
        ),
        migrations.AddField(
            model_name="personalplan",
            name="voice_report_daily_limit",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="صفر لتعطيل التفريغ في الباقة؛ الباقة الأساسية المجانية لا تمنح استخدامًا مدفوعًا.",
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="تسجيلات التقارير يوميًا",
            ),
        ),
        migrations.RunPython(enable_existing_paid_plans, migrations.RunPython.noop),
    ]
