# Generated by Django 5.2.17 on 2026-09-01 12:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


PROJECTS = (
    {
        "slug": "tawtheeq",
        "name": "منصة توثيق",
        "base_url": "https://tawtheeq-ksa.com",
        "health_path": "/healthz/",
        "compose_project": "school_reports",
        "repository": "xmansx2030-lgtm/school_reports",
        "ci_workflow": "ci.yml",
        "deploy_workflow": "ci.yml",
        "deploy_container": "school-reports-web-1",
    },
    {
        "slug": "xmansx",
        "name": "منصة TANAL",
        "base_url": "https://xmansx.com",
        "health_path": "/api/health/readiness",
        "compose_project": "tanal",
        "repository": "xmansx2030-lgtm/tanal",
        "ci_workflow": "ci.yml",
        "deploy_workflow": "deploy.yml",
        "deploy_container": "tanal-web-1",
    },
    {
        "slug": "school-display",
        "name": "لوحة العرض المدرسية",
        "base_url": "https://school-display.com",
        "health_path": "/",
        "compose_project": "school_display",
        "repository": "xmansx2030-lgtm/school_display",
        "ci_workflow": "ci.yml",
        "deploy_workflow": "deploy.yml",
        "deploy_container": "school-display-web-1",
    },
)


def sync_known_inventory(apps, schema_editor):
    ManagedServer = apps.get_model("operations", "ManagedServer")
    ManagedProject = apps.get_model("operations", "ManagedProject")
    server = ManagedServer.objects.filter(slug="school-reports-prod").first()
    if server is None:
        return
    for order, project in enumerate(PROJECTS, start=1):
        ManagedProject.objects.filter(slug=project["slug"]).update(
            server=server,
            name=project["name"],
            base_url=project["base_url"],
            health_path=project["health_path"],
            compose_project=project["compose_project"],
            repository=project["repository"],
            deploy_branch="main",
            ci_workflow=project["ci_workflow"],
            deploy_repository=project["repository"],
            deploy_workflow=project["deploy_workflow"],
            deploy_container=project["deploy_container"],
            deployment_enabled=True,
            sort_order=order,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0007_use_xmansx2030_school_reports_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="managedproject",
            name="compose_project",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="last_runtime_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="managedproject",
            name="runtime_status",
            field=models.CharField(
                choices=[
                    ("healthy", "سليم"),
                    ("degraded", "متدهور"),
                    ("down", "متوقف"),
                    ("maintenance", "صيانة"),
                    ("unknown", "غير معروف"),
                ],
                db_index=True,
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="managedproject",
            name="base_url",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
        migrations.CreateModel(
            name="ProjectMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpu_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=6, null=True
                    ),
                ),
                (
                    "memory_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "memory_used_mb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                (
                    "network_rx_mb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=14, null=True
                    ),
                ),
                (
                    "network_tx_mb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=14, null=True
                    ),
                ),
                (
                    "block_read_mb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=14, null=True
                    ),
                ),
                (
                    "block_write_mb",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=14, null=True
                    ),
                ),
                ("container_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "running_container_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("container_states", models.JSONField(blank=True, default=list)),
                (
                    "captured_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="operations.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["project", "-captured_at"],
                        name="operations__project_b51972_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(sync_known_inventory, migrations.RunPython.noop),
    ]
