# Generated by Django 5.2.17 on 2026-09-23 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0009_register_mizaan_server_managed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsPaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("customer_name", models.CharField(max_length=160)),
                ("customer_phone", models.CharField(max_length=32)),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                ("description", models.CharField(max_length=255)),
                (
                    "internal_reference",
                    models.CharField(blank=True, db_index=True, default="", max_length=120),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway_invoice_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "gateway_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "قيد الإنشاء"),
                            ("initiated", "بانتظار الدفع"),
                            ("paid", "مدفوعة"),
                            ("failed", "فشلت"),
                            ("refunded", "مستردّة"),
                            ("canceled", "ملغاة"),
                            ("on_hold", "معلّقة"),
                            ("expired", "منتهية"),
                            ("voided", "مبطلة"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                (
                    "provider_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_payment_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_links",
                        to="operations.managedproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["project", "status", "-created_at"],
                        name="operations__project_f1e209_idx",
                    ),
                    models.Index(
                        fields=["status", "last_synced_at"],
                        name="operations__status_352e60_idx",
                    ),
                ],
            },
        ),
    ]
