# Generated by Django 5.2.17 on 2026-09-25 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0011_operationspaymentlink_paid_notification_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HostAgentHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="primary", max_length=40, unique=True),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.AddField(
            model_name="operationaction",
            name="log_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="operationaction",
            name="log_content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="operationaction",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="operationaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("check_now", "فحص الآن"),
                    ("restart_service", "إعادة تشغيل خدمة"),
                    ("reload_proxy", "إعادة تحميل الوكيل"),
                    ("create_backup", "إنشاء نسخة احتياطية"),
                    ("read_logs", "قراءة السجلات"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ProviderAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("provider_action_id", models.BigIntegerField(blank=True, null=True)),
                ("status", models.CharField(default="requested", max_length=20)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_actions",
                        to="operations.managedserver",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "-id"),
            },
        ),
    ]
